#!/bin/bash
# A script to compile any paper tex file with biblatex
# Compile with ./compile {}

compile="com" 
compile_ref="ref"
clean="cle" 
filename="demresearchmobility" 

if [ -z $1 ]; then
    echo "Missing argument (either com, ref, cle)"
    exit
elif [ $1 = $clean ]; then
	echo "Cleaning please wait ..."
	rm -f *~
	rm -rf *.aux
	rm -rf *.bbl
	rm -rf *.blg
	rm -rf *.d
	rm -rf *.fls
	rm -rf *.ilg
	rm -rf *.ind
	rm -rf *.toc*
	rm -rf *.lot*
	rm -rf *.lof*
	rm -rf *.log
	rm -rf *.idx
	rm -rf *.out*
	rm -rf *.nlo
	rm -rf *.nls
        rm -rf *.bcf
        rm -rf *.run.xml
	rm -rf $filename.pdf
	rm -rf $filename.ps
	rm -rf $filename.dvi
	rm -rf *#* 
	echo "Cleaning complete!"
	exit
elif [ $1 = $compile_ref ]; then
    echo "Compiling your paper...please wait...!"
    pdflatex -interaction=nonstopmode $filename
    biber $filename 	
    pdflatex -interaction=nonstopmode $filename
    pdflatex -interaction=nonstopmode $filename
    okular $filename.pdf
	echo "Success!"
	exit
elif [ $1 = $compile ]; then
    echo "Compiling your paper...please wait...!"
    pdflatex -interaction=nonstopmode $filename
    okular $filename.pdf
	echo "Success!"
	exit
fi
